apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-service
  namespace: reference-service-showcase
  labels:
    app.kubernetes.io/name: reference-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-service
    spec:
      containers:
        - name: reference-service
          image: nzacharia/ref-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
           requests:
             memory: "300Mi"
             cpu: "0.1"
           limits:
             memory: "750Mi"
             cpu: "1.5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toxiproxy
  namespace: reference-service-showcase
  labels:
    app.kubernetes.io/name: toxiproxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: toxiproxy-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: toxiproxy-service
    spec:
      containers:
        - name: toxiproxy
          image: ghcr.io/shopify/toxiproxy
          ports:
            - containerPort: 8474
              name: toxiproxy-api
            - containerPort: 8686
              name: db-proxy              
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: reference-service-showcase
  labels:
    app.kubernetes.io/name: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:6.2.2
          ports:
            - containerPort: 9898


