apiVersion: apps/v1
kind: Deployment
metadata:
  name: reference-service
  namespace: reference-service-showcase
  labels:
    app.kubernetes.io/name: reference-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: reference-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reference-service
    spec:
      containers:
        - name: reference-service
          image: nzacharia/ref-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: reference-service-showcase
  labels:
    app.kubernetes.io/name: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:6.2.2
          ports:
            - containerPort: 9898


