apiVersion: v1
kind: Service
metadata:
  name: reference-service
  namespace: reference-service-showcase
spec:
  selector:
    app.kubernetes.io/name: reference-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: toxiproxy-service
  namespace: reference-service-showcase
spec:
  selector:
    app.kubernetes.io/name: toxiproxy-service
  type: NodePort
  ports:
    - name: toxiport
      protocol: TCP
      port: 8474
      targetPort: 8474
    - name: dbport
      protocol: TCP
      port: 8686
      targetPort: 8686
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: reference-service-showcase
spec:
  selector:
    app.kubernetes.io/name: podinfo
  ports:
    - protocol: TCP
      port: 9898
      targetPort: 9898
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reference-service
  namespace: reference-service-showcase
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: reference-service
                port:
                  number: 80
    - http:
        paths:
          - path: /toxiproxy(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: toxiproxy-service
                port:
                  number: 8474
