---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: &labels
    app: {{ .Release.Name }}
    track: {{ .Values.track }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.referenceport.serviceport }}
      targetPort: {{ .Values.referenceport.containerport }}
  selector: *labels