---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: &labels
    app: canary-{{ .Release.Name }}
    track: {{ .Values.canary.track }}
spec:
  replicas: {{ .Values.canary.replicas }}
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.canary.image.tag }}"
          imagePullPolicy: Never
          ports:
            - name: {{ .Values.referenceport.name }}
              containerPort: {{ .Values.referenceport.containerport }}
            - name: {{ .Values.canary.metricsport.name }}
              containerPort: {{ .Values.canary.metricsport.containerport }}
          resources:
           requests:
             memory: "{{ .Values.resources.requests.memory }}"
             cpu: "{{ .Values.resources.requests.cpu }}"
           limits:
             memory: "{{ .Values.resources.limits.memory }}"
             cpu: "{{ .Values.resources.limits.cpu }}"