---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-canary
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-canary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "{{ .Values.canary.weight }}"
    nginx.ingress.kubernetes.io/canary-by-header: "X-Canary"
spec:
  rules: 
     - http:
        paths:
          - path: /service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: canary-{{ .Release.Name }}
                port:
                  name: http